### PR TITLE
 Add String() methods to all components of the routing connector

### PR DESCRIPTION
**Pull request by phliar**

### CODE REVIEW

**Comment by skywhat** [comment]
Could I get more context why we need this change?

**Comment by skywhat** [comment]
> Could I get more context why we need this change?
I got it. I saw this task. T3411623

**Comment by skywhat** [comment]
would we get this new version released? if so, gateway imports new one and integration tests get fixed

**Comment by phliar** [comment]
Not just about that particular task: in general all types should have a good `String()` method that will help in debugging. (Sometimes a plain `"%+v"` is enough, but not always.)

**Comment by phliar** [comment]
> would we get this new version released? if so, gateway imports new one and integration tests get fixed

I don't need this released immediately. If you have a change that you want to include in a gateway build, we can release them together.

**Pull request merged**
